name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
             -t daniyaalabbas/my-k8s-web:${{ github.sha }} \
             -t daniyaalabbas/my-k8s-web:latest \
             .

      - name: Push Docker Image
        run: |
          docker push daniyaalabbas/my-k8s-web:latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment my-k8s-web
          - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/my-k8s-web --timeout=180s

      - name: Verify Deployment
        run: |
          kubectl get deploy
          kubectl get pods -o wide
          kubectl get svc

      - name: Smoke Test
        run: |
          sleep 10
             curl -I http://$(minikube ip):31749
