name: Terraform Infrastructure

on:
  push:
    paths:
      - 'main.tf'
      - 'provider.tf'
      - 'variables.tf'
      - 'terraform.tfvars'

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

        - name: Debug Workspace
          run: |
            echo "PWD:"
               pwd
              
               echo "Workspace:"
               echo "$GITHUB_WORKSPACE"

               echo "Files:"
               ls -la

               echo "Terraform state:"
               ls -la terraform.tfstate || echo "terraform.tfstate NOT FOUND"

               echo "Terraform state list:"
               terraform state list || true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
